version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: WeeklyPlanner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/WeeklyPlanner -schemas=public -user=postgres
      -password=postgres -connectRetries=5 migrate
    volumes:
      - ./database:/flyway/sql
    depends_on:
      - db
volumes:
  db: 









